/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_zeinebajouter (void);
GtkWidget* create_zeinebmodifier (void);
GtkWidget* create_zeinebsupprimer_ (void);
GtkWidget* create_zeinebafficher (void);
GtkWidget* create_liste_medecins (void);
GtkWidget* create_liste_infirmiers (void);
GtkWidget* create_liste_responsables (void);
GtkWidget* create_utilisateurs_sexe (void);
GtkWidget* create_sarramodifier (void);
GtkWidget* create_sarraajouter (void);
GtkWidget* create_sarrasupprimer (void);
GtkWidget* create_sarratri (void);
GtkWidget* create_sarraaffichage (void);
